name: Deploy to IPFS (Hosted by CloudFlare)
on:
  workflow_dispatch:
    inputs:
      storefront:
        description: The storefront manifest
        required: true
jobs:
  theme:
    needs:
      - storefront
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: sergeysova/jq-action@v2
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install
      - name: Generate Theme
        run: yarn theme '${{ github.event.inputs.storefront }}'
      - name: Archive theme artifact
        uses: actions/upload-artifact@v2
        with:
          name: storefront-theme
          path: ant-theme-overrides.less
  deploy:
    runs-on: ubuntu-latest
    needs:
      - storefront
      - theme
    steps:
      - uses: actions/setup-node@v2
      - uses: sergeysova/jq-action@v2
      - uses: actions/checkout@v2
        with:
          repository: kespinola/metaplex
          ref: ant-theme-overrides
      - name: Download storefront theme
        uses: actions/download-artifact@v2
        with:
          name: storefront-theme
          path: js/packages/web
      - uses: actions/cache@v2
        with:
          path: '**/js/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/js/yarn.lock') }}
      - uses: actions/cache@v2
        with:
          path: '**/js/packages/web/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/js/packages/web/yarn.lock') }}
      - uses: actions/cache@v2
        with:
          path: '**/js/packages/common/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/js/packages/common/yarn.lock') }}
      - name: Yarn install
        working-directory: js
        run: yarn install
      - name: Build Metaplex
        working-directory: js
        env:
          CI: false
        run: REACT_APP_STORE_OWNER_ADDRESS_ADDRESS=$(echo '${{ github.event.inputs.storefront }}' | jq '.pubkey') yarn build
      - name: Export Static Next
        working-directory: js/packages/web
        run: yarn export
      - id: subdomain
        run: echo "::set-output name=value::$(echo '${{ github.event.inputs.storefront }}' | jq '.subdomain' | sed "s/\"//g")"
      - name: IPFS Deploy
        working-directory: js
        env:
          IPFS_DEPLOY_CLOUDFLARE__RECORD: ${{ format('_dnslink.{0}.holaespi.com', steps.subdomain.outputs.value) }}
          IPFS_DEPLOY_CLOUDFLARE__ZONE: ${{ secrets.IPFS_DEPLOY_CLOUDFLARE__ZONE }}
          IPFS_DEPLOY_PINATA__API_KEY: ${{ secrets.IPFS_DEPLOY_PINATA__API_KEY }}
          IPFS_DEPLOY_PINATA__SECRET_API_KEY: ${{ secrets.IPFS_DEPLOY_PINATA__SECRET_API_KEY }}
          IPFS_DEPLOY_CLOUDFLARE__API_TOKEN: ${{ secrets.IPFS_DEPLOY_CLOUDFLARE__API_TOKEN }}
        run: npx ipfs-deploy -p pinata -d cloudflare build/web
