name: Deploy to IPFS (Hosted by CloudFlare)
on:
  workflow_dispatch:
    inputs:
      wallet:
        description: The storefront owner's pubkey
        required: true
jobs:
  storefront:
    runs-on: ubuntu-latest
    outputs:
      manifest: ${{ steps.manifest.outputs.value }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install
      - id: manifest
        run: echo "::set-output name=value::$(yarn run --silent storefront ${{ github.event.inputs.wallet }})"
        env:
          NEXT_PUBLIC_ARWEAVE_HOST: arweave.ngrok.io
          NEXT_PUBLIC_ARWEAVE_PROTOCOL: https
          NEXT_PUBLIC_ARWEAVE_PORT: 443
  theme:
    needs:
      - storefront
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install
      - name: Generate Theme
        run: yarn theme '${{ needs.storefront.outputs.manifest }}'
      - name: Archive theme artifact
        uses: actions/upload-artifact@v2
        with:
          name: storefront-theme
          path: ant-theme-overrides.less
  deploy:
    environment: dev
    runs-on: ubuntu-latest
    needs:
      - storefront
      - theme
    steps:
      - uses: actions/setup-node@v2
      - uses: sergeysova/jq-action@v2
      - uses: actions/checkout@v2
        with:
          repository: kespinola/metaplex
          ref: ant-theme-overrides
      - name: Download storefront theme
        uses: actions/download-artifact@v2
        with:
          name: storefront-theme
          path: js/packages/web
      - uses: actions/cache@v2
        with:
          path: '**/js/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/js/yarn.lock') }}
      - name: Yarn install
        working-directory: js
        run: yarn install
      - name: Build Metaplex
        working-directory: js
        env:
          CI: false
          REACT_APP_STORE_OWNER_ADDRESS_ADDRESS: ${{ github.event.inputs.wallet }}
        run: yarn build
      - name: Export Static Next
        working-directory: js/packages/web
        run: yarn export
      - id: subdomain
        run: echo "::set-output name=value::$(echo '${{ needs.storefront.outputs.manifest }}' | jq '.subdomain' | sed 's/\"/'/g')"
      - name: IPFS Deploy
        working-directory: js
        env:
          IPFS_DEPLOY_CLOUDFLARE__RECORD: ${{ format('_dnslink.{0}.holaespi.com', steps.subdomain.outputs.value) }}
          IPFS_DEPLOY_CLOUDFLARE__ZONE: ${{ secrets.IPFS_DEPLOY_CLOUDFLARE__ZONE }}
          IPFS_DEPLOY_PINATA__API_KEY: ${{ secrets.IPFS_DEPLOY_PINATA__API_KEY }}
          IPFS_DEPLOY_PINATA__SECRET_API_KEY: ${{ secrets.IPFS_DEPLOY_PINATA__SECRET_API_KEY }}
          IPFS_DEPLOY_CLOUDFLARE__API_TOKEN: ${{ secrets.IPFS_DEPLOY_CLOUDFLARE__API_TOKEN }}
        run: npx ipfs-deploy -p pinata -d cloudflare build/web
